SimpleBlog.UI/Areas/Admin/Controllers/PostController.cs
using SimpleBlog.Entity.Entities;
using SimpleBlog.Service.Services;
using SimpleBlog.UI.Areas.Admin.Data.DTOs;
using SimpleBlog.UI.Areas.Admin.Data.VMs;
using SimpleBlog.Utility.ImageProcessing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.UI.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        PostService _postService;
        CategoryService _categoryService;
        AppUserService _appUserService;

        public PostController()
        {
            _postService = new PostService();
            _categoryService = new CategoryService();
            _appUserService = new AppUserService();
        }

        // GET: Admin/Post
        public ActionResult Create()
        {
            AddPostVM addPostVM = new AddPostVM()
            {
                Categories = _categoryService.GetActive(),
                AppUsers = _appUserService.GetDefault(x => x.Role != Entity.Entities.Role.Member)
            };

            return View(addPostVM);
        }

        [HttpPost]
        public ActionResult Create(Post data, HttpPostedFileBase Image)
        {
            List<string> UploadImagePaths = new List<string>();

            UploadImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadImagePaths[0];

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {
                data.ImagePath = ImageUploader.DefaultProfileImagePath;
                data.ImagePath = ImageUploader.DefaultXSmallProfileImagePath;
                data.ImagePath = ImageUploader.DefaultCruptedProfileImagePath;
            }
            else
            {
                data.ImagePath = UploadImagePaths[1];
                data.ImagePath = UploadImagePaths[2];
            }

            _postService.Add(data);
            return Redirect("/Admin/Post/List");
        }

        public ActionResult List()
        {
            List<Post> model = _postService.GetActive();
            return View(model);
        }

        public ActionResult Details(int id)
        {
            Post post = _postService.GetById(id);
            return View(post);
        }

        public ActionResult Update(int id)
        {
            Post post = _postService.GetById(id);
            UpdatePostVM model = new UpdatePostVM();
            model.PostDTO.Id = post.Id;
            model.PostDTO.Header = post.Header;
            model.PostDTO.Content = post.Content;
            model.PostDTO.ImagePath = post.ImagePath;
            model.Categories = _categoryService.GetActive();
            model.AppUsers = _appUserService.GetActive();
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(PostDTO data, HttpPostedFileBase Image)
        {
            Post post = _postService.GetById(data.Id);

            List<string> UploadImagePaths = new List<string>();

            UploadImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadImagePaths[0];

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {
                if (post.ImagePath == null || post.ImagePath == ImageUploader.DefaultProfileImagePath)
                {
                    post.ImagePath = ImageUploader.DefaultProfileImagePath;
                    post.ImagePath = ImageUploader.DefaultXSmallProfileImagePath;
                    post.ImagePath = ImageUploader.DefaultCruptedProfileImagePath;
                }
                else
                {
                    post.ImagePath = data.ImagePath;
                }
            }
            else
            {
                post.ImagePath = UploadImagePaths[0];
                post.ImagePath = UploadImagePaths[1];
                post.ImagePath = UploadImagePaths[2];
            }

            post.Header = data.Header;
            post.Content = data.Content;
            post.CategoryId = data.CategoryId;
            post.AppUserId = data.AppUserId;
            post.Status = Status.Modified;
            post.UpdateDate = DateTime.Now;
            _postService.Update(post);
            return Redirect("/Admin/Post/List");
        }

        public ActionResult Delete(int id)
        {
            _postService.Remove(id);
            return Redirect("/Admin/Post/List");
        }
    }
}

SimpleBlog.UI/Areas/Member/Controllers/CommentController.cs
using SimpleBlog.Entity.Entities;
using SimpleBlog.Service.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.UI.Areas.Member.Controllers
{
    public class CommentController : Controller
    {
        CommentService _commentService;
        AppUserService _appUserService;
        LikeService _likeService;
        PostService _postService;

        public CommentController()
        {
            _commentService = new CommentService();
            _appUserService = new AppUserService();
            _likeService = new LikeService();
            _postService = new PostService();
        }

        // GET: Member/Comment
        public JsonResult AddComment(string userComment, int id)
        {
            Comment comment = new Comment();
            comment.AppUserId = _appUserService.FindByUserName(HttpContext.User.Identity.Name).Id;
            comment.PostId = id;
            comment.Content = userComment;

            bool isAdded = false;

            try
            {
                _commentService.Add(comment);
                isAdded = true;
            }
            catch (Exception)
            {
                isAdded = false;
            }

            return Json(isAdded, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteComment(int id)
        {
            int userId = _appUserService.FindByUserName(HttpContext.User.Identity.Name).Id;
            Comment comment = _commentService.GetById(id);

            bool isDelete = false;

            if (comment.AppUserId == userId)
            {
                isDelete = true;
                _commentService.Remove(id);
                return Json(isDelete, JsonRequestBehavior.AllowGet);
            }
            else
            {
                isDelete = false;
                return Json(isDelete, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult GetPostComment(int id)
        {
            Comment comment = _commentService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).LastOrDefault();

            return Json(new
            {
                AppUserImagePath = comment.AppUser.UserImage,
                FirstName = comment.AppUser.FirstName,
                LastName = comment.AppUser.LastName,
                CreateDate = comment.CreateDate.ToString(),
                Content = comment.Content,
                CommentCount = _commentService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count(),
                LikeCount = _commentService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count(),
            }, JsonRequestBehavior.AllowGet);

        }
    }
}

SimpleBlog.UI/Areas/Member/Controllers/LikeController.cs
using SimpleBlog.Entity.Entities;
using SimpleBlog.Service.Services;
using SimpleBlog.UI.Areas.Member.Data.VMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.UI.Areas.Member.Controllers
{
    public class LikeController : Controller
    {
        AppUserService _appUserService;
        LikeService _likeService;
        CommentService _commentService;

        public LikeController()
        {
            _appUserService = new AppUserService();
            _likeService = new LikeService();
            _commentService = new CommentService();
        }


        public JsonResult AddLike(int id)
        {
            JsonLikeVM jr = new JsonLikeVM();
            int appUserId = _appUserService.FindByUserName(HttpContext.User.Identity.Name).Id;

            if (!(_likeService.Any(x => x.AppUserId == appUserId && x.PostId == id)))
            {
                Like like = new Like();
                like.PostId = id;
                like.AppUserId = appUserId;
                _likeService.Add(like);

                jr.Likes = _likeService.GetDefault(x => x.PostId == id).Count();
                jr.userMessage = "like it";
                jr.isSuccess = true;
                jr.Likes = _likeService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count();
                jr.Comments = _commentService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count();
                return Json(jr, JsonRequestBehavior.AllowGet);
            }
            else
            {
                jr.isSuccess = false;
                jr.userMessage = "You've liked this post before..!";

                return Json(jr, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SimpleBlog.UI/Areas/Member/Controllers/PostController.cs
using SimpleBlog.Entity.Entities;
using SimpleBlog.Service.Services;
using SimpleBlog.UI.Areas.Member.Data.VMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleBlog.UI.Areas.Member.Controllers
{
    public class PostController : Controller
    {
        PostService _postService;
        AppUserService _appUserService;
        CategoryService _categoryService;
        CommentService _commentService;
        LikeService _likeService;

        public PostController()
        {
            _postService = new PostService();
            _appUserService = new AppUserService();
            _categoryService = new CategoryService();
            _commentService = new CommentService();
            _likeService = new LikeService();
        }

        // GET: Member/Post
        public ActionResult Show(int id)
        {
            PostDetailVM model = new PostDetailVM();
            model.Post = _postService.GetById(id);
            model.AppUser = _appUserService.GetById(model.Post.AppUserId);
       

            model.Comments = _commentService.GetDefault(x => x.PostId == id && x.Status != Status.Passive);
            model.Likes = _likeService.GetDefault(x => x.PostId == id && x.Status != Status.Passive);



            model.CommentCount = _commentService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count;

            model.LikeCount = _likeService.GetDefault(x => x.PostId == id && x.Status != Status.Passive).Count;

            return View(model);
        }
    }
}

SimpleBlog.UI/Areas/Member/Views/Post/Show.cshtml
@{
    ViewBag.Title = "Show";
    Layout = "~/Areas/Member/Views/Shared/_MemberLayoutPage.cshtml";
}

@model SimpleBlog.UI.Areas.Member.Data.VMs.PostDetailVM


<section class="content">
    <div class="row">
        <div class="col-sm-8">
            <div class="box box-widget">
                <div class="box-header with-border">
                    <div class="user-block">
                        <img class="img-circle" src="@Model.AppUser.UserImage" alt="User Image">
                        <span class="username"><a href="#">@Model.AppUser.FirstName @Model.AppUser.LastName</a></span>
                        <span class="description">Shared publicly - @Model.Post.CreateDate.ToShortDateString()</span>
                    </div>
                    <!-- /.user-block -->

                </div>
                <!-- /.box-header -->
                <div class="box-body" id="postlist">
                    <img class="img-responsive pad" src="@Model.Post.ImagePath" alt="Photo">
                    <button type="button" class="btn btn-default btn-xs"><i class="fa fa-share"></i> Share</button>
                    @if (!Model.Post.Likes.Any(x => x.AppUser.UserName == User.Identity.Name))
                    {
                        string elementId = "message" + Model.Post.Id;
                        <button type="button" id="like" onclick="like(@Model.Post.Id)" class="btn btn-default btn-xs"><i class="fa fa-heart"></i> Like</button>
                        <span id="@elementId" style="display:none">Like you</span>
                    }

                    <span class="pull-right text-muted" id="commentcount">@Model.LikeCount likes - @Model.CommentCount comments</span>
                    <p>
                        <h5>@Model.Post.Header</h5>
                    </p>
                    <p>
                        @Model.Post.Content
                    </p>
                </div>
                <!-- /.box-body -->
                <div class="box-footer box-comments" id="dynamiccomment">
                    @foreach (var item in Model.Comments)
                    {@item.Id
                        <div class="box-comment" id="a_">

                            <img class="img-circle img-sm" src="@item.AppUser.UserImage" alt="User Image">

                            <div class="comment-text">
                                <span class="username">
                                    @item.AppUser.FirstName @item.AppUser.LastName
                                    <span class="text-muted pull-right">
                                        @item.CreateDate.ToShortDateString()<br />

                                        @if (item.AppUser.UserName == User.Identity.Name)
                                        {
                                            <!--commentdalete çalışmazsa 'item.Id' diye gönder-->
                                            <a href="" id="commentdelete" onclick="commentdelete(@item.Id)" type="button" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a>

                                            <button type="button" id="edit" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></button>
                                        }
                                    </span>
                                </span>
                                @item.Content
                            </div>
                            <!-- /.comment-text -->
                        </div>
                        <!-- /.box-comment -->
                    }
                </div>
                <!-- /.box-footer -->
                <div class="box-footer">
                    <img class="img-responsive img-circle img-sm" src="@Session["ImagePath"]" alt="Alt Text">
                    <!-- .img-push is used to add margin to elements next to floating images -->
                    <div class="img-push">
                        <input type="text" id="comment" class="form-control input-sm" placeholder="Press enter to post comment">
                        <button type="button" id="addComment" onclick="comment(@Model.Post.Id)" class="btn btn-primary btn-xs">
                            <i class="fa fa-thumbs-o-up"></i>Comment
                        </button>
                        <span id="message" style="display:none">Have Comments</span>
                    </div>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
</section>



<script>
    function commentdelete(id) {
        $.ajax({
            type: "POST",
            url: "@Url.Action("DeleteComment", "Comment")/" + id,
            success: function (data) {
                $("#a_" + id).fadeOut();
            }
        });
    }

    function comment(postId) {
        console.log(postId);
        var commentText = $("#comment").val();

        $.ajax({
            type: "POST",
            dataType: "Json",
            data: { userComment: commentText, id: postId },
            url: "@Url.Action("AddComment","Comment")",
            success: function (data) {
                if (data == true) {
                    $("#message").removeAttr("style");
                    $("#message").html("");
                    $("#message").append("Have Comments.").fadeIn(2000);

                    commentdynamiclist(postId);

                }
                else {
                    $("#message").removeAttr("style");
                    $("#message").html("");
                    $("#message").append("An error has occured.");
                }
            }
        });
    }

    function commentdynamiclist(id) {

        $.ajax({
            type: "POST",
            dataType: "Json",
            url: "@Url.Action("GetPostComment", "Comment")/" + id,
            success: function (data) {
                if (data != null) {
                    $("#dynamiccomment").append('<div class="box-comment" id="lastcomment"><img class="img-circle img-sm" src="' + data.AppUserImagePath + '" alt="User Image"><div class="comment-text"><span class="username">' + data.FirstName + " " + data.LastName + '<span class="text-muted pull-right">' + data.CreateDate + '<br/><a href="" id="commentdelete" type="button" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></a><button type="button" id="edit" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></button></span></span>' + data.Content + '</div></div>');
                    $("#commentcount").hide().fadeOut(2000);
                    $("#postlist").append('<span class="pull-right text-muted" id="commentcount">' + data.LikeCount + ' likes - ' + data.CommentCount + ' comments</span>');
                    $("#comment").val("");
                    $("message").fadeOut(2000);
                    $("#lastcomment").hide().fadeIn(2000);
                }
                else {
                    //birşeyler yaparız aleet malert
                }
            }
        });
    }

    function like(id) {
        $.ajax({
            type: "POST",
            dataType: "Json",
            url: "@Url.Action("AddLike", "Like")/" + id,
            success: function (data) {
                if (data.isSuccess = true) {
                    $("#message" + id).removeAttr("");
                    $("#like").remove();
                    $("message" + id).html("");
                    $("message" + id).append(data.userMessage);
                    $("#commentcount").hide().fadeOut(2000);
                    $("#postlist").append('<span class="pull-right text-muted" id="commentcount">' + data.LikeCount + ' likes - ' + data.CommentCount + ' comments</span>');
                }
                else {
                    $("#message" + id).removeAttr("");
                    $("#like").remove();
                    $("#message" + id).html("");
                    $("#message" + id).append(data.userMessage);
                }
            }
        });
    }

</script>